name: moodmatch
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  modal_progress_hud: ^0.1.3
  http: ^0.12.2
  flushbar: ^1.10.4
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/back.png
    - lib/assets/images/copy.png
    - lib/assets/images/edit.png
    - lib/assets/images/fire_gradient.png
    - lib/assets/images/history.png
    - lib/assets/images/settings.png
    - lib/assets/images/snowflake.png
    - lib/assets/images/firegrey.png
    - lib/assets/images/snowflakegrey.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom assets.fonts to your application, add a assets.fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "assets.fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoLocal
      fonts:
        - asset: lib/assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Roboto-Thin.ttf
          weight: 300
        - asset: lib/assets/fonts/Roboto-ThinItalic.ttf
          weight: 300
          style: italic

#
  # For details regarding assets.fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
